import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import Footer from "@/components/Footer";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Roboto({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        
        {children}
        <Footer/>
        </body>
    </html>
  );
}
